"""Generate interview questions targeted at this candidate's specific gaps.

This is the feature that answers the original brief: give the interviewer a real
picture of the candidate before the conversation starts.

The value is entirely in the targeting. "Tell me about a challenging project" is
worthless and a model will happily produce twenty of them. What is useful is a
question aimed at a named uncertainty in *this* resume against *this* role:

* a must-have with partial evidence, where the interview should establish depth,
* a requirement the samples disagreed on, where the model itself was unsure,
* a claim the extractor could not ground, which may be a parsing artefact or may
  be worth confirming,
* a bullet with no measurable outcome, where the candidate's actual contribution
  is unclear.

So the prompt is given the gaps and nothing else. It never sees the score, the
band, or a recommendation, because a model told a candidate is weak writes
sceptical questions and a model told they are strong writes soft ones, and the
interviewer would inherit an anchoring bias generated by us.
"""

from __future__ import annotations

import logging

from hirelens.config import Settings, get_settings
from hirelens.llm.base import LLMError
from hirelens.llm.client import LLMClient
from hirelens.schemas.assessment import (
    CandidateAssessment,
    InterviewQuestion,
    RawInterviewPack,
    Verdict,
)
from hirelens.schemas.resume import CitedResume

logger = logging.getLogger(__name__)

SYSTEM_MESSAGE = """\
You write interview questions for a hiring manager preparing a first-round \
conversation. You are given specific uncertainties about one candidate, and you \
write questions that would resolve them.

Rules:

1. SPECIFIC, NOT GENERIC. Every question must reference the actual gap or claim \
you were given. Never write "Tell me about a challenging project" or "What are \
your strengths".
2. ONE UNCERTAINTY PER QUESTION.
3. OPEN AND NEUTRAL. Ask what they did, how it worked, what they would change. \
Do not write leading or sceptical questions, and never imply the candidate is \
exaggerating. The interviewer needs information, not a cross-examination.
4. NEVER ask about age, family, nationality, visa status, health, religion, \
politics, salary history, or anything about a university's reputation. These are \
unlawful or discriminatory in many jurisdictions and are irrelevant regardless.
5. For each question give a one-line rationale explaining what it would resolve, \
addressed to the interviewer.
6. Write 4 to 7 questions. Return JSON only.\
"""


def build_prompt(gaps: list[str], role_title: str) -> str:
    listed = "\n".join(f"- {gap}" for gap in gaps)
    role = role_title or "the role"
    return (
        f"The candidate is being considered for: {role}\n\n"
        f"Uncertainties to resolve in the interview:\n{listed}\n\n"
        f"Write questions that would resolve these specific uncertainties."
    )


# Cap the number of gaps sent. Beyond this the prompt gets long and the model
# starts producing shallow questions across everything instead of good ones on
# what matters most.
_MAX_GAPS = 8


def collect_gaps(assessment: CandidateAssessment, resume: CitedResume) -> list[str]:
    """The specific uncertainties worth an interview question, most important first."""
    gaps: list[str] = []

    # Unmet must-haves first: these decide the hire.
    for item in assessment.unmet_must_haves:
        gaps.append(
            f"Must-have '{item.requirement_text}' has no clear supporting evidence in the resume."
        )

    # Partial evidence on anything: the interview should establish depth.
    for item in assessment.assessments:
        if item.verdict is Verdict.PARTIAL:
            gaps.append(f"'{item.requirement_text}' has partial evidence only: {item.reasoning}")

    # Where the system itself was inconsistent, a human should probe.
    for item in assessment.needs_review:
        if not any(item.requirement_text in gap for gap in gaps):
            gaps.append(
                f"'{item.requirement_text}' produced inconsistent assessments; the "
                f"evidence is borderline."
            )

    # Claims that could not be traced back to the document.
    for quote in resume.grounding.unlocatable_quotes[:2]:
        gaps.append(f"This claim could not be verified against the document text: '{quote}'")

    # Achievements with no measurable outcome.
    vague = [
        highlight.value
        for job in resume.work
        for highlight in job.highlights
        if not any(character.isdigit() for character in highlight.value)
    ]
    for claim in vague[:2]:
        gaps.append(f"Achievement stated without a measurable outcome: '{claim}'")

    return gaps[:_MAX_GAPS]


class InterviewPackGenerator:
    """Produces targeted interview questions."""

    def __init__(
        self, client: LLMClient | None = None, *, settings: Settings | None = None
    ) -> None:
        self.settings = settings or get_settings()
        self.client = client or LLMClient(settings=self.settings)

    async def generate(
        self, assessment: CandidateAssessment, resume: CitedResume
    ) -> list[InterviewQuestion]:
        """Generate questions, or an empty list if there is nothing to probe."""
        gaps = collect_gaps(assessment, resume)
        if not gaps:
            logger.debug("no gaps worth probing for %s", assessment.document_id)
            return []

        try:
            pack = await self.client.structured(
                RawInterviewPack,
                system=SYSTEM_MESSAGE,
                user=build_prompt(gaps, assessment.role_title),
                # Slightly warm: identical phrasing across every candidate makes
                # the pack feel like a template and defeats the point.
                temperature=max(self.settings.judge_temperature, 0.4),
            )
        except LLMError as exc:
            # An interview pack is a nice-to-have. Losing it must not cost the
            # assessment, which is the actual deliverable.
            logger.warning("interview pack generation failed: %s", exc)
            return []

        return pack.questions[:7]
